### ISSUE TITLE
Segfault in kivy_.py when opening popup window

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#237]
Change start_url to "http://jegger.ch/datapool/app/test_popup.html".

Stack trace:
```
0x00007fffe7afb173 in (anonymous namespace)::life_span_handler_on_before_close(_cef_life_span_handler_t*, _cef_browser_t*) ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/cefpython_py27.so
(gdb) bt
#0  0x00007fffe7afb173 in (anonymous namespace)::life_span_handler_on_before_close(_cef_life_span_handler_t*, _cef_browser_t*) ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/cefpython_py27.so
#1  0x00007ffff16c6a50 in CefRenderProcessHandlerCToCpp::OnBrowserDestroyed(CefRefPtr<CefBrowser>)
    () from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#2  0x00007ffff16f2e31 in CefBrowserHostImpl::DestroyBrowser() ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#3  0x00007ffff16fdaca in CefBrowserInfoManager::DestroyAllBrowsers() ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#4  0x00007ffff1707f61 in CefContext::Shutdown() ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#5  0x00007ffff1707872 in (anonymous namespace)::CefForceShutdown::~CefForceShutdown() ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#6  0x00007ffff78331a9 in __run_exit_handlers (status=1, listp=0x7ffff7bb56c8 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#7  0x00007ffff78331f5 in __GI_exit (status=<optimized out>) at exit.c:104
#8  0x00007fffee7c5408 in _XDefaultError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#9  0x00007fffee7c554b in _XError () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#10 0x00007fffee7c25e7 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#11 0x00007fffee7c2695 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#12 0x00007fffee7c315d in _XReadEvents () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#13 0x00007fffee7c1718 in XWindowEvent () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#14 0x00007ffff23c05b4 in ui::X11EventSource::BlockUntilWindowMapped(unsigned long) ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#15 0x00007ffff17dfa17 in CefWindowX11::Show() ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#16 0x00007ffff17dd456 in CefBrowserPlatformDelegateNativeLinux::CreateHostWindow() ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#17 0x00007ffff16ed52d in CefBrowserHostImpl::CreateInternal(CefStructBase<CefBrowserSettingsTraits> const&, CefRefPtr<CefClient>, content::WebContents*, scoped_refptr<CefBrowserInfo>, CefRefPtr<CefBrowserHostImpl>, bool, CefRefPtr<CefRequestContext>, std::unique_ptr<CefBrowserPlatformDelegate, std::default_delete<CefBrowserPlatformDelegate> >) ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
---Type <return> to continue, or q <return> to quit---
#18 0x00007ffff16f672c in CefBrowserHostImpl::WebContentsCreated(content::WebContents*, int, std::string const&, GURL const&, content::WebContents*) ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#19 0x00007ffff46af06a in content::WebContentsImpl::CreateNewWindow(content::SiteInstance*, int, int, int, ViewHostMsg_CreateWindow_Params const&, content::SessionStorageNamespace*) ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#20 0x00007ffff45ed1c4 in content::RenderViewHostImpl::CreateNewWindow(int, int, int, ViewHostMsg_CreateWindow_Params const&, content::SessionStorageNamespace*) ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#21 0x00007ffff17ff6dc in base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask const&) () from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#22 0x00007ffff1817915 in base::MessageLoop::RunTask(base::PendingTask const&) ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#23 0x00007ffff1817c38 in base::MessageLoop::DeferOrRunPendingTask(base::PendingTask const&) ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#24 0x00007ffff1817dfb in base::MessageLoop::DoWork() ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#25 0x00007ffff17f6f9a in base::(anonymous namespace)::WorkSourceDispatch(_GSource*, int (*)(void*), void*) () from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#26 0x00007ffff0570e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff0571048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff05710ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff17f6e76 in base::MessagePumpGlib::Run(base::MessagePump::Delegate*) ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#30 0x00007ffff182d550 in base::RunLoop::Run() ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#31 0x00007ffff16ff34a in base::MessageLoop::RunUntilIdle() ()
   from /home/czarek/github/cefpython/src/linux/binaries_64bit/libcef.so
#32 0x00007fffe7a1898e in __pyx_pf_14cefpython_py27_24MessageLoopWork (__pyx_self=<optimized out>)
    at cefpython.cpp:75572
#33 __pyx_pw_14cefpython_py27_25MessageLoopWork (__pyx_self=<optimized out>, 
    unused=<optimized out>) at cefpython.cpp:9974
#34 0x000000000049a3b5 in PyEval_EvalFrameEx ()
---Type <return> to continue, or q <return> to quit---
#35 0x00000000004a090c in PyEval_EvalCodeEx ()
#36 0x000000000049ab45 in PyEval_EvalFrameEx ()
#37 0x0000000000499ef2 in PyEval_EvalFrameEx ()
#38 0x0000000000499ef2 in PyEval_EvalFrameEx ()
#39 0x0000000000499ef2 in PyEval_EvalFrameEx ()
#40 0x0000000000499ef2 in PyEval_EvalFrameEx ()
#41 0x0000000000499ef2 in PyEval_EvalFrameEx ()
#42 0x0000000000499ef2 in PyEval_EvalFrameEx ()
#43 0x00000000004a090c in PyEval_EvalCodeEx ()
#44 0x0000000000499a52 in PyEval_EvalFrameEx ()
#45 0x0000000000499ef2 in PyEval_EvalFrameEx ()
#46 0x00000000004a1634 in ?? ()
#47 0x000000000044e4a5 in PyRun_FileExFlags ()
#48 0x000000000044ec9f in PyRun_SimpleFileExFlags ()
#49 0x000000000044f904 in Py_Main ()
#50 0x00007ffff7818f45 in __libc_start_main (main=0x44f9c2 <main>, argc=2, argv=0x7fffffffdec8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdeb8) at libc-start.c:287
#51 0x0000000000578c4e in _start ()
```

**Comment by cztomczak** [comment]
Fixed by installing X11 error handlers:
```
         #init CEF
+        cefpython.WindowUtils.InstallX11ErrorHandlers()
         cefpython.Initialize(settings)
```
