### ISSUE TITLE
cefpython 0.48 doesn't work on portable python 2.7.3.1 on windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cztomczak/cefpython#39]
```
Portable Python is a convenient way to distribute python applications across 
Windows users, as there's no need to pre-install anything in advance (including 
PyWin32). However, CEF 0.48 doesn't run on Portable Python environment due to 
lack of some C libraries.

To reproduce: please, get a Portable Python at 
http://www.portablepython.com/wiki/PortablePython2.7.3.1, extract it and try to 
execute cefpython on it.

OS: Windows XP, Windows 7
```

Original issue reported on code.google.com by `eugeny.blokhin@gmail.com` on 5 Dec 2012 at 11:36

**Comment by TheInitializer** [comment]
hi, I'm still having this issue on portable Python 3.6.5. It gives me this message:

```
Traceback (most recent call last):
  File "tutorial.py", line 1, in <module>
    from cefpython3 import cefpython as cef
  File "<home>\Python36-32\lib\site-packages\cefpython3\__init__.py", line 59, in <module>
    from . import cefpython_py36 as cefpython
ImportError: DLL load failed: The specified path is invalid.
```
