### ISSUE TITLE
MemoryError in PaintBuffer.GetString when running screenshot.py example on Python 3.7

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#443]
Logs:
```
C:\github\cefpython\build>python ..\examples\screenshot.py
[screenshot.py] CEF Python 66.0
[screenshot.py] Chromium 66.0.3359.181
[screenshot.py] CEF 3.3359.1774.gd49d25f
[screenshot.py] Python 3.7.0 32bit
[screenshot.py] Pillow 5.2.0
[screenshot.py] Viewport size: (1024, 5000)
[screenshot.py] Loading url: https://github.com/cztomczak/cefpython

DevTools listening on ws://127.0.0.1:51658/devtools/browser/747fa141-4e4f-43d7-926d-5e5d172dbdfa
[screenshot.py] OnPaint[CEF Python] ExceptHook: catched exception, will shutdown CEF

Traceback (most recent call last):
  File "render_handler.pyx", line 207, in cefpython_py37.RenderHandler_OnPaint
  File "..\examples\screenshot.py", line 209, in OnPaint
  File "paint_buffer.pyx", line 71, in cefpython_py37.PaintBuffer.GetString
  File "paint_buffer.pyx", line 100, in cefpython_py37.PaintBuffer.GetString
MemoryError
```

**Comment by cztomczak** [comment]
Issue doesn't occur anymore. Earlier I've had OS warnings about low memory. Revision 4a1d759 exposes PaintBuffer attrs: length, width, height. Buffer length = 20 MB and there are multiple OnPaint calls. Also a copy of the buffer is made through a call to Browser.SetUserData. Thus the script can be using lots of memory.
