### ISSUE TITLE
Crash on exit when closing browser immediately during initial loading

### ISSUE THREAD

**Issue by cztomczak** [cztomczak/cefpython#454]
Reproducible in gtk2.py example on Windows. Error:

```
Traceback (most recent call last):
  File "..\examples\gtk2.py", line 176, in on_exit
    self.browser.CloseBrowser(True)
  File "browser.pyx", line 330, in cefpython_py27.PyBrowser.CloseBrowser
  File "browser.pyx", line 341, in cefpython_py27.PyBrowser.CloseBrowser
  File "browser.pyx", line 185, in cefpython_py27.PyBrowser.GetCefBrowserHost
  File "browser.pyx", line 180, in cefpython_py27.PyBrowser.GetCefBrowser
Exception: PyBrowser.GetCefBrowser() failed: CefBrowser was destroyed
```

**Comment by cztomczak** [comment]
Fixed in commit 66107b2.
