### ISSUE TITLE
Support for Mingw32/Cygwin compiler in build tools

### ISSUE THREAD

**Issue by hugonun** [cztomczak/cefpython#525]
I am trying to install cefpython on MinGW to use it with GTK, but I get the following:

```
$ pip3 install cefpython3
      1 [main] python3 4740 child_info_fork::abort: address space needed by 'msys-ssl-1.1.dll' (0x7B0000) is already occupied
Collecting cefpython3
  ERROR: Could not find a version that satisfies the requirement cefpython3 (from versions: none)
ERROR: No matching distribution found for cefpython3
```

I also tried with `pip install cefpython3==66.0`.

**Comment by cztomczak** [comment]
What Python distribution do you use? Only standard distribution from Python.org is supported. CEF Python module is built with Python Tools for Visual Studio on Windows. If you want to build it with a different compiler then see the Build Instructions document.

**Comment by hugonun** [comment]
I have been following [this](https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-logo-windows) to get PyGObject working on Windows, and it uses `pacman -S mingw-w64-x86_64-python3`, I assume using the standard one isn't an option.

I'm not familiar with building something on MSYS2, but I'll do my best.

**Comment by hugonun** [comment]
No success, I got stuck here:

```
  File "C:/Users/user/Desktop/python/webkit/b/cefpython-master/tools/build_cpp_projects.py", line 115, in get_compiler
    compiler.initialize()
AttributeError: 'Mingw32CCompiler' object has no attribute 'initialize'
[build.py] ERROR: Failed to compile C++ projects
```

**Comment by cztomczak** [comment]
You will have to fix any errors with Mingw32. For example to fix this specific error, go to `python/lib/distutils/` and find `cygwinccompiler.py`. In that file the `Mingw32CCompiler` class is missing the `initialize` method. It seems that it is not required to call it. Fix cefpython tool by editing this line https://github.com/cztomczak/cefpython/blob/d635effdd5d96072a3e899e8fb32ca4d8cf78d63/tools/build_cpp_projects.py#L115 . Change it so that `initialize` method is not called for Mingw32CCompiler. If you make it work with Mingw32 you could send a PR.

**Comment by cztomczak** [comment]
I've renamed the issue and am reopening it. Support for Mingw32/Cygwin compiler in build tools is something that we might want to have, as it shouldn't be hard to support. Although there is no plan to provide mingw32 specific module for now.

If you make it work I suggest you use the setup package to install it, as installing with pip might require more changes to the wheel packaging tools.

On the Python.org WindowCompilers wiki page you can find this information:
> Some alternative compilers exist like MinGW, but incompatibilities may occur with a CPython official distribution that is built with Microsoft Visual C++.

It says that issues may occur, but not necessarily? You can try building cefpython3 using MSVC compiler and then use the setup package to install it with the command `python setup.py install` instead of using the wheel package with pip.

**Comment by hugonun** [comment]
Thank you for helping me out!

I didn't manage to build it with MSVC, I got this:

```
[buil_cpp_projects.py] Build executable: subprocess
Traceback (most recent call last):
  File "C:\Users\HugsPC\Desktop\python\webkit\cef\cefpython-master\tools\build_cpp_projects.py", line 316, in <module>
    main()
  File "C:\Users\HugsPC\Desktop\python\webkit\cef\cefpython-master\tools\build_cpp_projects.py", line 78, in main
    build_subprocess_executable()
  File "C:\Users\HugsPC\Desktop\python\webkit\cef\cefpython-master\tools\build_cpp_projects.py", line 164, in build_subprocess_executable
    compiler = get_compiler(static=True)
  File "C:\Users\HugsPC\Desktop\python\webkit\cef\cefpython-master\tools\build_cpp_projects.py", line 117, in get_compiler
    compiler.compile_options.remove("/MD")
ValueError: list.remove(x): x not in list
[build.py] ERROR: Failed to compile C++ projects
```

So I commented that line, but then I got [this](https://pastebin.com/2CF292EX).

So I tried to go back to MinGW, I commented the init part out, but now I got this:

```
[build_cpp_projects.py] Build library: cefpython_app
gcc: error: /EHsc: No such file or directory
Traceback (most recent call last):
  File "C:/msys32/mingw64/lib/python3.7\distutils\cygwinccompiler.py", line 171, in _compile
    extra_postargs)
  File "C:/msys32/mingw64/lib/python3.7\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:/msys32/mingw64/lib/python3.7\distutils\spawn.py", line 39, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:/msys32/mingw64/lib/python3.7\distutils\spawn.py", line 78, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:/msys32/mingw64/bin/gcc.exe' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/HugsPC/Desktop/python/webkit/cef/cefpython-master/tools/build_cpp_projects.py", line 316, in <module>
    main()
  File "C:/Users/HugsPC/Desktop/python/webkit/cef/cefpython-master/tools/build_cpp_projects.py", line 69, in main
    build_cefpython_app_library()
  File "C:/Users/HugsPC/Desktop/python/webkit/cef/cefpython-master/tools/build_cpp_projects.py", line 159, in build_cefpython_app_library
    output_dir=BUILD_CEFPYTHON_APP)
  File "C:/Users/HugsPC/Desktop/python/webkit/cef/cefpython-master/tools/build_cpp_projects.py", line 140, in build_library
    output_dir=output_dir)
  File "C:/Users/HugsPC/Desktop/python/webkit/cef/cefpython-master/tools/build_cpp_projects.py", line 282, in smart_compile
    extra_postargs=extra_args)
  File "C:/msys32/mingw64/lib/python3.7\distutils\ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "C:/msys32/mingw64/lib/python3.7\distutils\cygwinccompiler.py", line 173, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:/msys32/mingw64/bin/gcc.exe' failed with exit status 1
[build.py] ERROR: Failed to compile C++ projects
```

Note that I'm using Cython version 0.29.7 because was no MinGW build for the required version.

**Comment by cztomczak** [comment]
It complains about `/EHsc` flag which is not understood by Mingw. You can find occurences of it using github search: https://github.com/cztomczak/cefpython/search?utf8=%E2%9C%93&q=EHsc&type=
