### ISSUE TITLE
examples/pyinstaller/ does not work

### ISSUE THREAD

**Issue by markfink** [cztomczak/cefpython#531]
I just tried the **examples/pyinstaller** and it did not work (on arch linux).
altgraph==0.16.1
cefpython3==66.0
PyInstaller==3.5

...just wanted to let you know ;)

``` Python
$ ./dist/pyinstaller/pyinstaller 
Traceback (most recent call last):
  File "pyinstaller.py", line 17, in <module>
    import PyInstaller
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/mark/tmp/cefpythonc/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/PyInstaller/__init__.py", line 66, in <module>
  File "site-packages/pkg_resources/__init__.py", line 481, in get_distribution
  File "site-packages/pkg_resources/__init__.py", line 357, in get_provider
  File "site-packages/pkg_resources/__init__.py", line 900, in require
  File "site-packages/pkg_resources/__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'PyInstaller' distribution was not found and is required by the application
[13810] Failed to execute script pyinstaller
```

**Comment by cztomczak** [comment]
From your logs it appears that "import PyInstaller" fails which suggests something is wrong with PyInstaller package. You should report your problem to Pyinstaller issue tracker.

As a side note pyinstaller scripts were tested with pyinstaller versions 3.2.1, 3.3 and 3.4.

**Comment by cztomczak** [comment]
Similar issues with pyinstaller:
https://www.google.com/search?q=pkg_resources.DistributionNotFound%3A+The+%27PyInstaller%27+distribution+was+not+found+and+is+required+by+the+application

**Comment by markfink** [comment]
I just wanted to let you know that it is not working (I checked pyinstaller 3.4 and it does not work either).
Thanks for the googling :)

**Comment by cztomczak** [comment]
It does not work because pyinstaller was not installed correctly or your virtual environment is broken.
