### ISSUE TITLE
ImportError: cannot import name 'byte_string'

### ISSUE THREAD

**Issue by noval102200** [cztomczak/cefpython#564]
Questions should be asked on the forum:
https://groups.google.com/group/cefpython
When i run python pyinstaller.py,it occur error below:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.5', 'console_scripts', 'pyinstaller')()
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "pyinstaller.spec", line 39, in <module>
    cipher_obj = PyiBlockCipher(key=SECRET_CIPHER)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 54, in __init__
    self._aesmod = import_aes(get_crypto_hiddenimports())
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 37, in get_crypto_hiddenimports
    import_aes(modname)
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\archive\pyz_crypto.py", line 21, in import_aes
    return __import__(module_name, fromlist=[module_name.split('.')[-1]])
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\Crypto\Cipher\__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "c:\users\administrator\appdata\local\programs\python\python36-32\lib\site-packages\Crypto\Util\_raw_api.py", line 33, in <module>
    from Crypto.Util.py3compat import byte_string
ImportError: cannot import name 'byte_string'
Error: PyInstaller failed, code=1

**Comment by cztomczak** [comment]
Do not create issues in the tracker.
