### ISSUE TITLE
pyinstaller error

### ISSUE THREAD

**Issue by step123456789** [cztomczak/cefpython#572]
Questions should be asked on the forum:
https://groups.google.com/group/cefpython
108 INFO: PyInstaller: 3.2.1
108 INFO: Python: 3.7.3
109 INFO: Platform: Windows-10-10.0.17763-SP0
110 INFO: UPX is not available.
111 INFO: Removing temporary files and cleaning cache in ...\AppData\Roaming\pyinstaller
134 INFO: Extending PYTHONPATH with paths
['G:\\cefpython-master\\examples']
134 INFO: Will encrypt Python bytecode with key: This-is-a-secret
135 INFO: Adding dependencies on pyi_crypto.py module
135 INFO: checking Analysis
136 INFO: Building Analysis because out00-Analysis.toc is non existent
136 INFO: Initializing module dependency graph...
139 INFO: Initializing module graph hooks...
140 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "d:\install_soft\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\install_soft\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\install_soft\Anaconda3\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 48, in <module>
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\depend\analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\depend\analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "d:\install_soft\anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
Error: PyInstaller failed, code=1

**Comment by cztomczak** [comment]
Looks like pyinstaller 3.2.1 has issues with scanning "base_library.zip" for your Python version. You can try upgrade pyinstaller to a newer version, but keep in mind that cefpython's pyinstaller example is only tested with 3.2.1 and users reported issues with newer versions of pyinstaller in the past, so other unrelated issues might arise if you do so.

**Comment by step123456789** [comment]
Thanks for your response. I have replaced python 3.7.3 with 3.6.5, but it still got the same error.

**Comment by step123456789** [comment]
I tried python 3.5 and I got the cefapp.exe, but a new error occurs:
-------------------------------------------------------------------------------------------------------
PyInstaller Bootloader 3.x
LOADER: executable is G:\cefpython-master\examples\pyinstaller\dist\cefapp\cefapp.exe
LOADER: homepath is G:\cefpython-master\examples\pyinstaller\dist\cefapp
LOADER: _MEIPASS2 is NULL
LOADER: archivename is G:\cefpython-master\examples\pyinstaller\dist\cefapp\cefapp.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(G:\cefpython-master\examples\pyinstaller\dist\cefapp)
LOADER: Already in the child - running user's code.
LOADER: Python library: G:\cefpython-master\examples\pyinstaller\dist\cefapp\python35.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is G:\cefpython-master\examples\pyinstaller\dist\cefapp\base_library.zip;G:\cefpython-master\examples\pyinstaller\dist\cefapp
LOADER: sys.prefix is G:\cefpython-master\examples\pyinstaller\dist\cefapp
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is G:\cefpython-master\examples\pyinstaller\dist\cefapp\base_library.zip;G:\cefpython-master\examples\pyinstaller\dist\cefapp
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted pyimod00_crypto_key
LOADER: callfunction returned...
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running wxpython.py
Traceback (most recent call last):
  File "wxpython.py", line 10, in <module>
ImportError: No module named 'wx'
Failed to execute script wxpython
LOADER: OK.
LOADER: Cleaning up Python interpreter.

**Comment by step123456789** [comment]
I installed wxpython 4.0 and it succeeded! Thanks a lot.
