### ISSUE TITLE
Kivy - SendMouseMoveEvent with modifier not working

### ISSUE THREAD

**Issue by hoba87** [cztomczak/cefpython#574]
When trying to integrate cefpython into kivy, the SendMouseMoveEvent with the modifier for a pressed MouseButton, e.g. cef.EVENTFLAG_LEFT_MOUSE_BUTTON, is not working for me.

See also the pull request for the updated kivy example [https://github.com/cztomczak/cefpython/pull/573](https://github.com/cztomczak/cefpython/pull/573), which let me run the example on Win10.

For an easy check, the website [http://nglviewer.org/ngl/?script=showcase/ferredoxin](http://nglviewer.org/ngl/?script=showcase/ferredoxin) is good, which allow to rotate and move the structure by a pressed mouse button and mouse move in a webbrowser, but not with the kivy example.

Is there a solution or workaround?

**Comment by cztomczak** [comment]
Are you reporting issue with the kivy_.py example? This example is supported only on Linux.

**Comment by hoba87** [comment]
Yes, I know that it was not intended to support other OS, however with the new pull request commit, it is at least working on Windows now, except this described issue.

**Comment by cztomczak** [comment]
Are you running the kivy_.py example from the PR as is, or did you make any other modifications? What exactly isn't working, dragging?

**Comment by hoba87** [comment]
Yes, running the kivy_.py from PR as is. The "touch move" is not working, so moving the mouse while pressing left or right mouse button.
Dragging is also not working.

**Comment by cztomczak** [comment]
Do you need to comment out the browser switches to reproduce the issue?

**Comment by hoba87** [comment]
To open the website from above yes, because it uses WebGL, otherwise I get only the message that WebGL is not supported.
The pywin32.py example works with the website by the way.

**Comment by cztomczak** [comment]
Can you test a different website with SendMouseMoveEvent ?

**Comment by cztomczak** [comment]
Can you test a different website with SendMouseMoveEvent ? With no modifications to kivy_.py (just as is in PR).

**Comment by hoba87** [comment]
Do you know a website where I can test it? I've googled around but have not find another one.

What I've tried: click on the google logo on google.com and "move" it. It works on MacOS, however it seems to be a drag event. (E.g. dragging an image to google pic search does not work)
On Windows I get an error: 
```
Traceback (most recent call last):
  File "render_handler.pyx", line 263, in cefpython_py36.RenderHandler_StartDragging
  File "C:/cefpython/src/linux/binaries_64bit/kivy_.py", line 964, in StartDragging
    drag_data, x, y, cef.DRAG_OPERATION_EVERY)
  File "browser.pyx", line 788, in cefpython_py36.PyBrowser.DragTargetDragEnter
OverflowError: can't convert negative value to uint32_t
```

**Comment by hoba87** [comment]
Ah, ok after thinking again I've tried google maps. Yes it is working both on MacOS and Win.

**Comment by cztomczak** [comment]
If you remove the disable-gpu* flags rendering can be much slower. It might be that CPU is overloaded and events are being lost. Try lower frame rate.

I am not sure why WebGL doesn't work. v66 includes swiftshader (unless you've removed the swiftshader/ subdirectory in the cefpython3 package) which provides software rendering for GPU.

**Comment by hoba87** [comment]
Ok, for Windows the website is also loading with disable-gpu* flags, it seems I've tested that only on Mac before.
However the touch move is not working, neither on mac nor on win with soft- or hardware rendering. Lowering the frame rate doesn't help and the cpu is not overloaded.

**Comment by cztomczak** [comment]
So now it's an issue with Kivy's on_touch_move, not with SendMouseMoveEvent?

**Comment by hoba87** [comment]
Well, probably it is not an issue with kivys on_touch_move because it is executed as verified by using google maps (and by adding a print command printing something).
And perhaps also not an issue with SendMouseMoveEvent, also because of google maps test.
The website from above is mainly based on javascript, could there be the issue?

**Comment by cztomczak** [comment]
You will have to debug it to find the cause of the issue.

**Comment by cztomczak** [comment]
See if there are any errors in Developer Tools console.

**Comment by hoba87** [comment]
Arghh, it's a Heisenbug.
When I use the ShowDevTools() function, it is working, both on Win and Mac. It also keeps working if I close the dev tools manually or by CloseDevTools().
The "direct" remote_debugging_port doesn't work (the link is there, but opens an empty site only) and doesn't help.
The DevTools for Node works also like a Heisenbug, when the DevTools are opened, I can rotate the structure.

I'm not familiar with the DevTools but I cannot see any errors.

**Comment by cztomczak** [comment]
Check if message loop is being called every 10ms or so. Looks like events are lost due to message loop not working correctly. Try enabling external_message_pump on other OSes and see if it makes any difference. When you open devtools in a window that uses windowed rendering it runs message loop using a different way.

**Comment by hoba87** [comment]
the _meesage_loop_work function is called about every 5ms. external_message_pump does not make a difference for win.

**Comment by cztomczak** [comment]
5ms would be too often and might cause issues.

**Comment by hoba87** [comment]
changing it to about 10ms by removing the kivy "hack" makes no difference

**Comment by hoba87** [comment]
Should I add the workaround to the pull request? At the moment I have no clue what to try else.

**Comment by cztomczak** [comment]
What workaround?

**Comment by hoba87** [comment]
using 
ShowDevTools()
CloseDevTools()

**Comment by cztomczak** [comment]
No, I don't think so. You can try creating a hidden window on startup and see if that helps.
