### ISSUE TITLE
Can not renderring html content

### ISSUE THREAD

**Issue by xuqiang-idotools** [cztomczak/cefpython#606]
I got the below info on loading local html content with protocal "data:text/html".
How to fix the issue ? Thanks!

Uncaught DOMException: Failed to read the 'cookie' property from 'Document': Cookies are disabled inside 'data:' URLs.
    at o (https://g.alicdn.com/sd/ncpc/nc.js:2:21441)
    at s (https://g.alicdn.com/sd/ncpc/nc.js:2:22262)
    at Object.l [as getNCToken] (https://g.alicdn.com/sd/ncpc/nc.js:2:22300)
    at Object.<anonymous> (https://g.alicdn.com/sd/ncpc/nc.js:2:25876)
    at t (https://g.alicdn.com/sd/ncpc/nc.js:1:418)
    at Object.<anonymous> (https://g.alicdn.com/sd/ncpc/nc.js:5:30650)
    at t (https://g.alicdn.com/sd/ncpc/nc.js:1:418)
    at Object.<anonymous> (https://g.alicdn.com/sd/ncpc/nc.js:5:810)
    at t (https://g.alicdn.com/sd/ncpc/nc.js:1:418)
    at Object.t.makeNC (https://g.alicdn.com/sd/ncpc/nc.js:4:7230)
punishpage.min.js:1 Uncaught TypeError: window.noCaptcha is not a function
    at punishpage.min.js:1
    at HTMLScriptElement.<anonymous> (punishpage.min.js:1)

**Comment by cztomczak** [comment]
As the error says. Cookies are disabled inside data: urls. Use other type of url.
