### ISSUE TITLE
 PyRequest.GetPostData    'bytes' object has no attribute 'encode'

### ISSUE THREAD

**Issue by hanziqi1** [cztomczak/cefpython#626]
window10,cefpython==66.1  @cztomczak 
Traceback (most recent call last):
  File "request_handler.pyx", line 117, in cefpython_py38.RequestHandler_OnBeforeResourceLoad
  File "D:\workspace\browser_cef\rebulid_cef.py", line 36, in OnBeforeResourceLoad
    post_data = request.GetPostData()
  File "request.pyx", line 83, in cefpython_py38.PyRequest.GetPostData
  File "request.pyx", line 130, in cefpython_py38.PyRequest.GetPostData
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by cztomczak** [comment]
Here is the code that fails: https://github.com/cztomczak/cefpython/blob/5679f28cec18a57a56e298da2927aac8d8f83ad6/src/request.pyx#L129

Related issues: https://github.com/cztomczak/cefpython/issues?q=is%3Aissue+GetPostData+is%3Aclosed

**Comment by hanziqi1** [comment]
> Here is the code that fails:
> 
> https://github.com/cztomczak/cefpython/blob/5679f28cec18a57a56e298da2927aac8d8f83ad6/src/request.pyx#L129
> 
> Related issues: https://github.com/cztomczak/cefpython/issues?q=is%3Aissue+GetPostData+is%3Aclosed
