### ISSUE TITLE
Error in line 65 .

### ISSUE THREAD

**Issue by Gowrishankar-atmega-robotics** [cztomczak/cefpython#636]
```
[INFO   ] [Logger      ] Record log in /home/atmegarobotics/.kivy/logs/kivy_21-12-01_13.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/usr/lib/python2.7/dist-packages/kivy/__init__.pyc"
[INFO   ] [Python      ] v2.7.17 (default, Feb 27 2021, 15:10:58) 
[GCC 7.5.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python"
[WARNING] [Deprecated  ] Python 2 Kivy support has been deprecated. The Kivy release after 1.11.0 will not support Python 2 anymore
 Traceback (most recent call last):
   File "try.py", line 2, in <module>
     from kivy.garden.cefpython import CefBrowser, cefpython
   File "/usr/lib/python2.7/dist-packages/kivy/garden/__init__.py", line 173, in load_module
     return self._load_module(fullname, moddir)
   File "/usr/lib/python2.7/dist-packages/kivy/garden/__init__.py", line 177, in _load_module
     ('', '', imp.PKG_DIRECTORY))
   File "/home/atmegarobotics/.kivy/garden/garden.cefpython/__init__.py", line 65
     if exists(libcef):
                      ^
 SyntaxError: invalid syntax

```
how to solve this issue

**Comment by cztomczak** [comment]
Looks like Python compatibility issue in garden.cefpython . That's an addon not supported here.
