### ISSUE TITLE
Chromium 100+ support

### ISSUE THREAD

**Issue by josephernest** [cztomczak/cefpython#652]
The current version `pip install cefpython3` only uses Chromium 66.

How to update to the latest stable Chromium (higher than version 100)?

**Comment by laulugs** [comment]
i had the same problem，please help with it .

**Comment by llcc01** [comment]
> The current version `pip install cefpython3` only uses Chromium 66.
> 
> How to update to the latest stable Chromium (higher than version 100)?

I have changed API to fit Chromium 108. You can try my unofficial version. https://github.com/llcc01/cefpython

**Comment by laulugs** [comment]
> > The current version `pip install cefpython3` only uses Chromium 66.
> > How to update to the latest stable Chromium (higher than version 100)?
> 
> I have changed API to fit Chromium 108. You can try my unofficial version. https://github.com/llcc01/cefpython

Thank you!

**Comment by shakraw** [comment]
@llcc01 @cztomczak  could you help me on build your unofficial version on Windows x86 ? I'm trying to follow the docs but I get these errors as soon as starting ```c:\Python37\python.exe ..\tools\automate.py --prebuilt-cef``` command.
I've downloaded a prebuilt CEF version from here: https://cef-builds.spotifycdn.com/index.html#windows32:108.4.13
Any thoughts / suggestions on this?
Thanks in advance!

```
C:\cefpython3\build>c:\Python37\python.exe ..\tools\automate.py --prebuilt-cef
[automate.py] Build cef projects...
[automate.py] Create build_cefclient/ dir in cef_binary*/ dir
[automate.py] Build cefclient, cefsimple, ceftests
[automate.py] Running 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat x86 && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..' in 'C:\cefpython3\build\cef_binary_108.4.13+ga98cd4c+chromium-108.0.5359.125_windows32\build_cefclient'...
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe - broken
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/cefpython3/build/cef_binary_108.4.13+ga98cd4c+chromium-108.0.5359.125_windows32/build_cefclient/CMakeFiles/CMakeScratch/TryCompile-bjh9d2

    Run Build Command(s):C:/dev/ninja.exe -v cmTC_d0c43 && [1/2] C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe  /nologo   /DWIN32 /D_WINDOWS  /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\cmTC_d0c43.dir\testCCompiler.c.obj /FdCMakeFiles\cmTC_d0c43.dir\ /FS -c C:\cefpython3\build\cef_binary_108.4.13+ga98cd4c+chromium-108.0.5359.125_windows32\build_cefclient\CMakeFiles\CMakeScratch\TryCompile-bjh9d2\testCCompiler.c
    [2/2] cmd.exe /C "cd . && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_d0c43.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo CMakeFiles\cmTC_d0c43.dir\testCCompiler.c.obj  /out:cmTC_d0c43.exe /implib:cmTC_d0c43.lib /pdb:cmTC_d0c43.pdb /version:0.0 /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    FAILED: cmTC_d0c43.exe
    cmd.exe /C "cd . && "C:\Program Files (x86)\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_d0c43.dir --rc=rc --mt=CMAKE_MT-NOTFOUND --manifests  -- C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo CMakeFiles\cmTC_d0c43.dir\testCCompiler.c.obj  /out:cmTC_d0c43.exe /implib:cmTC_d0c43.lib /pdb:cmTC_d0c43.pdb /version:0.0 /machine:X86  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /fo CMakeFiles\cmTC_d0c43.dir/manifest.res CMakeFiles\cmTC_d0c43.dir/manifest.rc" failed (exit code 0) with the following output:
    Impossibile trovare il file specificato
    ninja: build stopped: subcommand failed.





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:143 (project)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "..\tools\automate.py", line 1110, in <module>
    main()
  File "..\tools\automate.py", line 157, in main
    prebuilt_cef()
  File "..\tools\automate.py", line 301, in prebuilt_cef
    build_cef_projects()
  File "..\tools\automate.py", line 437, in build_cef_projects
    run_command(command, build_cefclient_dir)
  File "..\tools\automate.py", line 975, in run_command
    return subprocess.check_call(args, cwd=working_dir, env=env, shell=shell)
  File "c:\Python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat', 'x86', '&&', 'cmake', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=Release', '..']' returned non-zero exit status 1.
```

**Comment by ltavoletti** [comment]
> > The current version `pip install cefpython3` only uses Chromium 66.
> > How to update to the latest stable Chromium (higher than version 100)?
> 
> I have changed API to fit Chromium 108. You can try my unofficial version. https://github.com/llcc01/cefpython

Hi @llcc01 is a mac build also planned?

**Comment by llcc01** [comment]
> > > The current version `pip install cefpython3` only uses Chromium 66.
> > > How to update to the latest stable Chromium (higher than version 100)?
> > 
> > 
> > I have changed API to fit Chromium 108. You can try my unofficial version. https://github.com/llcc01/cefpython
> 
> Hi @llcc01 a build for mac is also planned?

Sorry, I have never tried any on mac. Maybe someone can do it.

**Comment by shakraw** [comment]
Hi all,
I created an unofficial version making some tries on top of @llcc01's fork to make it works on MacOS.
You can find it here: https://github.com/shakraw/cefpython

It compiles on both Windows/Mac.
On Windows I'm able to use it to browse sites but I see some issues I need to investigate further.
On Mac it compiles and builds the wheel package, but it doesn't pass the unit tests.

The output from the unit tests is as follow:
```
test_unittest1 (unittest_test.Test) ... ok
test_unittest2 (unittest_test.Test) ... ok
test_unittest3 (unittest_test.Test) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.001s

OK
test_isolated1 (isolated_test.IsolatedTest1) ... ok
test_isolated2 (isolated_test.IsolatedTest1) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.000s

OK
test_isolated3 (isolated_test.IsolatedTest2) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
test_main (main_test.MainTest_IsolatedTest)
Main entry point. All the code must run inside one ... test_osr (osr_test.OsrTest_IsolatedTest)
Main entry point. All the code must run inside one ... ----------------------------------------------------------------------
[_test_runner.py] CEF Python -unknown-
[_test_runner.py] Python 3.7.9 64bit
[_test_runner.py] Ran 8 tests in total
[_test_runner.py] FAILED (errors=1)
```

Checking the error on the failed test I see it gives a SEGFAULT very soon in the Initialize call in src/string_utils.pyx line 125 :
```
    # Using cefString.FromASCII() will result in DCHECK failures
    # when a non-ascii character is encountered.
    cefString.FromString(cppString)  # <-- SEGFAULT here
```

I'm not a c/c++ dev... anyone can help on this?

**Comment by lolouthefox** [comment]
> 

How do we install it tho?

**Comment by lolouthefox** [comment]
> > The current version `pip install cefpython3` only uses Chromium 66.
> > How to update to the latest stable Chromium (higher than version 100)?
> 
> I have changed API to fit Chromium 108. You can try my unofficial version. https://github.com/llcc01/cefpython

Awesome but how do we install it?
