### ISSUE TITLE
Exception: Python version not supported: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]

### ISSUE THREAD

**Issue by TinTin-Esoterico** [cztomczak/cefpython#674]
Hello!
There is any issue with Python 3.12.4? Reading this thread [(issue 624)](https://github.com/cztomczak/cefpython/issues/624) you said to take a look at `Lib\site-packages\cefpython3\__init__.py`, and the last lines of my cefpython (v66.1) are 
```
elif sys.version_info[:2] == (3, 9):
    # noinspection PyUnresolvedReferences
    from . import cefpython_py39 as cefpython
else:
    raise Exception("Python version not supported: " + sys.version)
```
can I just add 3,12 here?

**Comment by TinTin-Esoterico** [comment]
Nah I cant, this give the error

`ImportError: DLL load failed while importing cefpython_py39: The specified module could not be found.`

**Comment by y3team** [comment]
+1

**Comment by XLTechie** [comment]
Hi @cztomczak 
I am experiencing this same issue. I've tried Python 3.11.9, and 3.12.6, with the same results.

I'm using it on a GitHub actions windows-latest builder, so I know it is a pristine installation.
`pip install cefpython3`

After pyinstaller builds any version of a simple hello world program which imports cefpython, I get the following:

```
Failed to execute script 'main' due to unhandled exception: Python version not supported: 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]

Traceback (most recent call last):
  File "main.pyw", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "cefpython3\__init__.py", line 74, in <module>
Exception: Python version not supported: 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
```

This is most frustrating.
